language: node_js
node_js: node
services: mongodb
deploy:
  provider: heroku
  api_key:
    secure: jRMzjCZedS1lA829KN5EGum3nAblpyR/0zLWMUb2uwzrOhx1COUMSwdplbZ8vaHqcfMjxbNdImUnfeUBzUJziJDaFVfcBQD/IZqt5fwPsUWyd0vrKlAGZctOBu7NiipispdDXq4aIVsVRz9n+S5W/LWah7L/V94Y6slpCAwCiutuAc3yAX+jJw4jURdVc5nRzpGQdBJzXtalbeWL0dL1kNR8gT0PY9Lbzs1CH+fxFF5rrOwrkvKDFoJvyvErbXxepouewYe6d+6+scMe1qVyFAXzIGhTiKlzk7kSt/7LentMdEZ64pW7w+15zYXmhCTE8Chx72sUEDn2rHkbNvdnljrNm/5mSchSDXao+yt3rutGAb1jRs0hipHw3nyDRKBgJIqOTvciEl8QJy/A1b/SGZn10g2aSVjHgmFLZ82z03IOrhEqqFvcj3ncnlim74ccos6k1fSp2CFMZjCx7lfw72qwMk+EKtw2zT/gSJnjmeGbT+ONhSSOl5N3l2pbQX4Fo5v532jfIwn0c3Tx/C+P3JK37NQVg74GTTlbgZvFf614VEDgVS9+VE2fEEgZlTZUXdS7Wj/O7LEd2mWRSbBSAKfmI9+tJmyLfHEU8+kDn2tLQVglkI5WFtaJspla3oiWSahifLSrrGuSfPju7YHyLzc5Wg7LPGUQJxtrlkLYjoE=
  app: ChrisG-noteful-v3
  on:
    repo: thinkful-ei23/ChrisG-noteful-v3
